config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount SolidusPaypalCommercePlatform::Engine, at: '/solidus_paypal_commerce_platform'
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    resources :products
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
end

app/models/spree/products.rb
# frozen_string_literal: true

module Spree
  # Products represent an entity for sale in a store. Products can have
  # variations, called variants. Product properties include description,
  # permalink, availability, shipping category, etc. that do not change by
  # variant.
  class Product < Spree::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: :history

    include Spree::SoftDeletable

    after_discard do
      variants_including_master.discard_all
      self.product_option_types = []
      self.product_properties = []
      classifications.destroy_all
      self.product_promotion_rules = []
    end

    has_many :product_option_types, dependent: :destroy, inverse_of: :product
    has_many :option_types, through: :product_option_types

    has_many :product_properties, dependent: :destroy, inverse_of: :product
    has_many :properties, through: :product_properties
    has_many :variant_property_rules
    has_many :variant_property_rule_values, through: :variant_property_rules, source: :values
    has_many :variant_property_rule_conditions, through: :variant_property_rules, source: :conditions

    has_many :classifications, dependent: :delete_all, inverse_of: :product
    has_many :taxons, through: :classifications, before_remove: :remove_taxon

    has_many :product_promotion_rules, dependent: :destroy
    has_many :promotion_rules, through: :product_promotion_rules

    belongs_to :tax_category, class_name: 'Spree::TaxCategory', optional: true
    belongs_to :shipping_category, class_name: 'Spree::ShippingCategory', inverse_of: :products, optional: true

    has_one :master,
            -> { where(is_master: true).with_discarded },
            inverse_of: :product,
            class_name: 'Spree::Variant',
            autosave: true

    has_many :variants,
             -> { where(is_master: false).order(:position) },
             inverse_of: :product,
             class_name: 'Spree::Variant'

    has_many :variants_including_master,
             -> { order(:position) },
             inverse_of: :product,
             class_name: 'Spree::Variant',
             dependent: :destroy

    has_many :prices, -> { order(Spree::Variant.arel_table[:position].asc, Spree::Variant.arel_table[:id].asc, :currency) }, through: :variants_including_master

    has_many :stock_items, through: :variants_including_master

    has_many :line_items, through: :variants_including_master
    has_many :orders, through: :line_items

    scope :sort_by_master_default_price_amount_asc, lambda {
      with_default_price.order('spree_prices.amount ASC')
    }
    scope :sort_by_master_default_price_amount_desc, lambda {
      with_default_price.order('spree_prices.amount DESC')
    }
    scope :with_default_price, lambda {
      left_joins(master: :prices).
        where(master: { spree_prices: Spree::Config.default_pricing_options.desired_attributes })
    }

    def find_or_build_master
      master || build_master
    end

    MASTER_ATTRIBUTES = %i(
      cost_currency
      cost_price
      depth
      height
      price
      sku
      weight
      width
    ).freeze
    MASTER_ATTRIBUTES.each do |attr|
      delegate :"#{attr}", :"#{attr}=", to: :find_or_build_master
    end

    delegate :amount_in,
             :display_amount,
             :display_price,
             :has_default_price?,
             :images,
             :price_for,
             :price_for_options,
             :rebuild_vat_prices=,
             to: :find_or_build_master

    alias master_images images

    has_many :variant_images, -> { order(:position) }, source: :images, through: :variants_including_master

    after_create :build_variants_from_option_values_hash, if: :option_values_hash

    after_destroy :punch_slug
    after_discard :punch_slug

    after_initialize :ensure_master

    after_save :run_touch_callbacks, if: :saved_changes?
    after_touch :touch_taxons

    before_validation :normalize_slug, on: :update
    before_validation :validate_master

    validates :meta_keywords, length: { maximum: 255 }
    validates :meta_title, length: { maximum: 255 }
    validates :name, presence: true
    validates :price, presence: true, if: proc { Spree::Config[:require_master_price] }
    validates :shipping_category_id, presence: true
    validates :slug, presence: true, uniqueness: { allow_blank: true, case_sensitive: true }

    attr_accessor :option_values_hash

    accepts_nested_attributes_for :variant_property_rules, allow_destroy: true
    accepts_nested_attributes_for :product_properties, allow_destroy: true, reject_if: ->(pp) { pp[:property_name].blank? }

    alias options product_option_types

    self.whitelisted_ransackable_associations = %w(stores variants_including_master master variants)
    self.whitelisted_ransackable_attributes = %w(name slug)

    def self.ransackable_scopes(_auth_object = nil)
      %i(with_discarded with_variant_sku_cont with_all_variant_sku_cont with_kept_variant_sku_cont)
    end

    # @return [Boolean] true if there are any variants
    def has_variants?
      variants.any?
    end

    # @return [Spree::TaxCategory] tax category for this product, or the default tax category
    def tax_category
      super || Spree::TaxCategory.find_by(is_default: true)
    end

    # Ensures option_types and product_option_types exist for keys in
    # option_values_hash.
    #
    # @return [Array] the option_values
    def ensure_option_types_exist_for_values_hash
      return if option_values_hash.nil?

      required_option_type_ids = option_values_hash.keys.map(&:to_i)
      self.option_type_ids |= required_option_type_ids
    end

    # Creates a new product with the same attributes, variants, etc.
    #
    # @return [Spree::Product] the duplicate
    def duplicate
      duplicator = ProductDuplicator.new(self)
      duplicator.duplicate
    end

    # Use for checking whether this product has been deleted. Provided for
    # overriding the logic for determining if a product is deleted.
    #
    # @return [Boolean] true if this product is deleted
    def deleted?
      !!deleted_at
    end

    # Determines if product is available. A product is available if it has not
    # been deleted, the available_on date is in the past
    # and the discontinue_on date is nil or in the future.
    #
    # @return [Boolean] true if this product is available
    def available?
      !deleted? && available_on&.past? && !discontinued?
    end

    # Determines if product is discontinued.
    #
    # A product is discontinued if the discontinue_on date
    # is not nil and in the past.
    #
    # @return [Boolean] true if this product is discontinued
    def discontinued?
      !!discontinue_on&.past?
    end

    # Poor man's full text search.
    #
    # Filters products to those which have any of the strings in +values+ in
    # any of the fields in +fields+.
    #
    # @param fields [Array{String,Symbol}] columns of the products table to search for values
    # @param values [Array{String}] strings to search through fields for
    # @return [ActiveRecord::Relation] scope with WHERE clause for search applied
    def self.like_any(fields, values)
      conditions = fields.product(values).map do |(field, value)|
        arel_table[field].matches("%#{value}%")
      end
      where conditions.inject(:or)
    end

    # @param pricing_options [Spree::Variant::PricingOptions] the pricing options to search
    #   for, default: the default pricing options
    # @return [Array<Spree::Variant>] all variants with at least one option value
    def variants_and_option_values_for(pricing_options = Spree::Config.default_pricing_options)
      variants.includes(:option_values).with_prices(pricing_options).select do |variant|
        variant.option_values.any?
      end
    end

    # Groups all of the option values that are associated to the product's variants, grouped by
    # option type.
    #
    # @param variant_scope [ActiveRecord_Associations_CollectionProxy] scope to filter the variants
    # used to determine the applied option_types
    # @return [Hash<Spree::OptionType, Array<Spree::OptionValue>>] all option types and option values
    # associated with the products variants grouped by option type
    def variant_option_values_by_option_type(variant_scope = nil)
      option_value_scope = Spree::OptionValuesVariant.joins(:variant).
        where(spree_variants: { product_id: id })
      option_value_scope = option_value_scope.merge(variant_scope) if variant_scope
      option_value_ids = option_value_scope.distinct.pluck(:option_value_id)
      Spree::OptionValue.where(id: option_value_ids).
        includes(:option_type).
        order("#{Spree::OptionType.table_name}.position, #{Spree::OptionValue.table_name}.position").
        group_by(&:option_type)
    end

    # @return [Boolean] true if there are no option values
    def empty_option_values?
      options.empty? || !option_types.left_joins(:option_values).where('spree_option_values.id IS NULL').empty?
    end

    # @param property_name [String] the name of the property to find
    # @return [String] the value of the given property. nil if property is undefined on this product
    def property(property_name)
      return nil unless prop = properties.find_by(name: property_name)

      product_properties.find_by(property: prop).try(:value)
    end

    # Assigns the given value to the given property.
    #
    # @param property_name [String] the name of the property
    # @param property_value [String] the property value
    def set_property(property_name, property_value)
      ActiveRecord::Base.transaction do
        # Works around spree_i18n https://github.com/spree/spree/issues/301
        property = Spree::Property.create_with(presentation: property_name).find_or_create_by(name: property_name)
        product_property = Spree::ProductProperty.where(product: self, property: property).first_or_initialize

app/controllers/potepan/products_controller.rb
# frozen_string_literal: true

# ProductsController
class Potepan::ProductsController < ApplicationController
  def index
    @products = Spree::Product.all
    @prices = Spree::Price.all
  end

  def show
    @product = Spree::Product.find(params[:id])
    @price = Spree::Price.find(params[:id])
  end

  private

  def product_params
    params.require(:Spree::Product).permit(:name, :images, :description)
  end

  def price_params
    params.require(:Spree::Price).permit(:amount)
  end
end

app/controllers/potepan/sample_controller.rb
# frozen_string_literal: true

# Potepan::SampleController
class Potepan::SampleController < ApplicationController
  def index; end

  def product_grid_left_sidebar; end

  def product_list_left_sidebar; end

  def single_product; end

  def cart_page; end

  def checkout_step_1; end

  def checkout_step_2; end

  def checkout_step_3; end

  def checkout_complete; end

  def blog_left_sidebar; end

  def blog_right_sidebar; end

  def blog_single_left_sidebar; end

  def blog_single_right_sidebar; end

  def about_us; end

  def tokushoho; end

  def privacy_policy; end
end

app/views/potepan/products/index.html.erb
<h1>indexのページ</h1>

<div>
   <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            
            <%= image_tag '/assets/product.jpg' %>
          </tr>
        <% end %>
  </div>

  <h1>ここから金額</h1>
  <div>
  <% @prices.each do |price| %>
          <tr>
            <td><%= price.id %></td>
            <td><%= price.amount %></td> 
          </tr>
        <% end %>
  </div>

app/views/potepan/products/show.html.erb
<div class="user-show-main">
         
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-xs-6">
              <div class="page-title">
                <h2><%= @product.name %></h2><!---->
              </div>
            </div>
            <div class="col-xs-6">
              <ol class="breadcrumb pull-right">
                <li>
                  <%= link_to "Home",potepan_index_path %>
                  
                </li>
                <li class="active"><%= @product.name %></li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix">
        <div class="container">
          <div class="row singleProduct">
            <div class="col-xs-12">
              <div class="media">
                <div class="media-left productSlider">
                      <div id="carousel" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                          <% @product.variant_images.each_with_index do |image, i| %>
                            <div class="item <%= 'active' if i == 0 %>" data-thumb="<%= i %>">
                              <%= image_tag image.attachment.url %>
                            </div>
                          <% end %>
                        </div>
                      </div>
                      
                  <div class="clearfix">
                    <div id="thumbcarousel" class="carousel slide" data-interval="false">
                      <div class="carousel-inner">
                         
                            <div >
                              <% @product.variant_images.each do |image| %>
                                   <div data-target="#carousel" data-slide-to="0" class="thumb">
                                     <%= image_tag image.attachment.url %>
                                   </div>
                              <% end %>
                          </div>
                      </div>
                      <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                      </a>
                      <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                      </a>
                    </div>
                  </div>
                </div>
                <div class="media-body">
                  <ul class="list-inline">
                    <li> <i class="fa fa-reply" aria-hidden="true"></i><%= link_to "一覧ページへ戻る",potepan_product_grid_left_sidebar_path %>
                    
                    <!-- <li><a href="#"><i class="fa fa-plus" aria-hidden="true"></i>Share This</a></li> -->
                  </ul>
                  <h2><%= @product.name %></h2><!---->
                  <h3>＄<%= @price.amount %></h3><!---->
                  <p><%= @product.description %></p>
                  <span class="quick-drop">
                    <select name="guiest_id3" id="guiest_id3" class="select-drop">
                      <option value="0">S</option>
                      <option value="1">M</option>
                      <option value="2">L</option>
                      <option value="3">XL</option>
                    </select>
                  </span>
                  <span class="quick-drop resizeWidth">
                    <select name="guiest_id4" id="guiest_id4" class="select-drop">
                         <!--   <option value="0">Qty</option> -->
                      <option value="1">1</option>
                      <option value="2">2</option>
                      <option value="3">3</option>
                    </select>
                  </span>
                  <div class="btn-area">
                     <%= link_to "カートに入れる",potepan_cart_page_path, class:'btn btn-primary btn-block'%>
                  </div>
                  <!-- <div class="tabArea">
                    <ul class="nav nav-tabs">
                      <li class="active"><a data-toggle="tab" href="#details">details</a></li>
                      <li><a data-toggle="tab" href="#about-art">about art</a></li>
                      <li><a data-toggle="tab" href="#sizing">sizing</a></li>
                      <li><a data-toggle="tab" href="#shipping">shipping</a></li>
                    </ul>
                    <div class="tab-content">
                      <div id="details" class="tab-pane fade in active">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        <ul class="list-unstyled">
                          <li>Black, Crew Neck</li>
                          <li>75% Cotton, 25% Rayon</li>
                          <li>Waterbased Ink</li>
                          <li>Wash Cold, dry low</li>
                        </ul>
                      </div>
                      <div id="about-art" class="tab-pane fade">
                        <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit vitae dignissim volutpat. </p>
                      </div>
                      <div id="sizing" class="tab-pane fade">
                        <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo facilisis, pulvinar convallis nunc.</p>
                      </div>
                      <div id="shipping" class="tab-pane fade">
                        <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
                      </div>
                    </div>
                  </div> -->
                </div>
              </div>
            </div>
          </div>
          <div class="row productsContent">
            <div class="col-xs-12">
              <div class="page-header">
                <h4>関連商品/</h4>
              </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="productBox">
                <div class="productImage clearfix">
                  <%= image_tag("img/products/products-01.jpg", :alt => "products-img") %>
                </div>
                <div class="productCaption clearfix">
                 <h5>Nike Sportswear</h5>
                 <h3>199円</h3>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="productBox">
                <div class="productImage clearfix">
                  <%= image_tag("img/products/products-02.jpg", :alt => "products-img") %>
                </div>
                <div class="productCaption clearfix">
                 <h5>Dip Dyed Sweater</h5>
                 <h3>249円</h3>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="productBox">
                <div class="productImage clearfix">
                  <%= image_tag("img/products/products-03.jpg", :alt => "products-img") %>
                </div>
                <div class="productCaption clearfix">
                 <h5>Scarf Ring Corner</h5>
                 <h3>179円</h3>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="productBox">
                <div class="productImage clearfix">
                  <%= image_tag("img/products/products-04.jpg", :alt => "products-img") %>
                </div>
                <div class="productCaption clearfix">
                 <h5>Sun Buddies</h5>
                 <h3>149円</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>
</div> 